site_name: Hardware
site_url: https://4d-game.github.io/Hardware

nav:
  - Home: https://4d-game.github.io
  - Working on this Project: https://4d-game.github.io/game_concept/
  - Game Code:
      - Controller: https://4d-game.github.io/Controller/
      - Gamecontrol: https://4d-game.github.io/Gamecontrol/
  - Game Hardware:
      - Overview: index.md
      - Tower: tower.md
      - Turrets: turrets.md
      - Displays: display.md
      - Components: components.md
  - SDK: https://4d-game.github.io/sdk/

repo_url: https://github.com/4D-Game/Hardware
repo_name: '4D-Game/Hardware'

theme:
  name: material
  language: en
  logo: pictures/logo.png
  favicon: pictures/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # - scheme: default
    #   primary: light blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - scheme: slate
      primary: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode

plugins:
  - search
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
