#!/usr/bin/env python3

import os
import toml
import argparse

PRESET_PATH = r'/etc/srtg/srtg.toml'
CONFIG_PATH = os.path.join(os.path.dirname(
    os.path.abspath(__file__)), '..', 'srtg.toml')

parser = argparse.ArgumentParser()

parser.add_argument("device_id", help="Name of the Streamer")
parser.add_argument("token", help="Gametoken")

args = parser.parse_args()

print(args)

config = toml.load(PRESET_PATH)

config["device_id"] = args.device_id
config["game_engine"]["token"] = args.token

print(config)

with open(CONFIG_PATH, 'w') as f:
    toml.dump(config, f)
