#!/bin/bash

SCRIPT_PATH=$(dirname `which $0`)

echo "Updatet packages ---------------------------------------------------------"
sudo apt update
sudo apt upgrade -y
echo ""

echo "Setup Shell environment --------------------------------------------------"
touch ~/.bash_profile
echo "export PYTHONPATH=$SCRIPT_PATH/../src" >> ~/.bash_profile
echo "export PATH=/home/$USER/.local/bin:$PATH"
source ~/.bash_profile
echo ""

# Install XBox controller support
# sudo apt install xboxdrv -y
# echo 'options bluetooth disable_ertm=Y' | sudo tee -a /etc/modprobe.d/bluetooth.conf

echo "Install Python and Pip ---------------------------------------------------"
sudo apt install python3 python3-pip -y
echo ""