#This controller configuration file is modified by automated tools. All comments will be lost when this is updated.
device_id = ""
watcherstream_mode = "obs"

[game_engine]
url =  "https://ge.surrogate.tv/signaling"
token = ""

[rtc_config]
[[rtc_config.ice_servers]]
urls = "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302,stun:stun2.l.google.com:19302,stun:stun3.l.google.com:19302,stun:stun4.l.google.com:19302"

[[sources]]
kind = "video"
label = "mainvideo"

[sources.video_params]
width = 1280
height = 720
framerate = 30

[[sources]]
kind = "audio"
label = "mainaudio"