#!/bin/bash

SCRIPT_PATH=$(dirname `which $0`)

echo "copying srtg.toml to /etc/srtg/srtg.toml"
sudo cp $SCRIPT_PATH/../controller.service /etc/srtg/srtg.toml

echo "restarting srtg service"
sudo systemctl restart srtg

echo "srtg service status"
sudo systemctl status srtg