site_name: Crazy Comet - Gamecontrol
site_url: https://4d-game.github.io/sdk

nav:
  - Home: https://4d-game.github.io
  - Working on this Project: https://4d-game.github.io/game_concept/
  - Game Code:
      - Controller: https://4d-game.github.io/Controller/
      - Gamecontrol: https://4d-game.github.io/Gamecontrol/
  - Game Hardware: https://4d-game.github.io/Hardware
  - SDK:
      - Getting Started: index.md
      - Controller:
          - Getting Started: controller-sdk/index.md
          - Key Maps: controller-sdk/key-maps.md
          - Config File: controller-sdk/config-file.md
      - Gamecontrol:
          - Getting Started: gamecontrol-sdk/index.md
          - Config File: gamecontrol-sdk/config-file.md
      - Passive:
          - Getting Started: passive-sdk/index.md
          - Config File: gamecontrol-sdk/config-file.md
      - Examples:
          - LED Test Game: examples/led-test-game.md
      - Code References:
          - GameTemplate: code-references/game.md
          - GameIO: code-references/game-io.md
          - Players: code-references/players.md
          - Controller:
              - Game: code-references/controller/game.md
              - inputs:
                  Input: code-references/controller/input.md
                  Joystick: code-references/controller/joystick.md
                  Switch: code-references/controller/switch.md
              - key_map: code-references/controller/key_map.md
          - Gamecontrol:
              - Game: code-references/gamecontrol/game.md
          - Passive:
              - Game: code-references/passive/game.md

repo_url: https://github.com/4D-Game/sdk
repo_name: 4D-Game/SDK

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # - scheme: default
    #   primary: light blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - scheme: slate
      primary: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      watch:
        - game_sdk
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
